[MLP-148] Add --no-api option to skip API files
MakingSense/mern-seed pull request #22
Opened 2017-03-16 17:06 UTC by matiasbeckerle

## Background

@juampick came with the idea of providing some optional parameters and one is `--no-api` to avoid including all the backend files because sometimes we rely on other APIs.

## Changes

- Added `--no-api` option.
- Conditionally add API files based on option provided.

## Notes

There was also another idea, about providing `--create`, `--read`, `--update` and `--delete` options but while I was doing that I've found that the template and generator code was started to look much more complex and way too difficult to read & maintain. I published another WIP branch if someone wants to resume that work but I discourage to do so (really, not nice). Here is the branch: https://github.com/matiasbeckerle/mern-seed/tree/MLP-148-crud-parameters-wip

2017-03-16 17:12 UTC, AlphaGit requested changes

2017-03-16 17:12 UTC, AlphaGit commented on cli/generators/crud/index.js
> +    this.option('api', {
Here the option is `api`, but the docs say `--no-api`. Maybe this one should be changed?

2017-03-16 17:15 UTC, matiasbeckerle commented on cli/generators/crud/index.js
> +    this.option('api', {
No. The `no-` prefix is like the negative version of your option. I didn't invest time on researching it but I believe is on purpose so you can use `--api` or `--no-api`. Actually I first tried with `no-api` but it doesn't work. I believe that if I dig a little bit on the documentation I will find the explanation...

2017-03-16 17:27 UTC, AlphaGit commented on cli/generators/crud/index.js
> +    this.option('api', {
Wonderful. I didn't know about that. Thanks!

2017-03-16 17:27 UTC, AlphaGit approved these changes

2017-03-17 20:16 UTC, juampick approved these changes
Thanks Matts @matiasbeckerle Great job! really neat

2017-03-17 20:16 UTC, merged

2017-03-17 20:39 UTC, matiasbeckerle commented
Appreciated @juampick!